services:
  app:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    command: >
      sh -c "composer install &&
             mkdir -p database &&
             touch database/database.sqlite &&
             php artisan key:generate &&
             php artisan migrate:fresh --seed &&
             php artisan serve --host=0.0.0.0 --port=8000"

  vite:
    image: node:20
    container_name: laravel_vite
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "5173:5173"
    command: >
      sh -c "npm install && npm run dev -- --host"
